### ISSUE TITLE
No Base Model

### ISSUE THREAD

**Issue by andela-sdamian** [andela-anwocha/checkpoint-one-music-lib#1]
You should have a base model for all your models where you put shared logic and interface for all other models. There is a whole lot of repetition in your code, in models like `Genre` and `Artist` you keep including and extending modules some of this method in this module can be kept in  your base model.

**Comment by andela-mpitan** [comment]
I think that is how they were told to do it
They should pass the test by putting those methods into a module, then they should include or extend those modules as the case may be.
Another option is to use a hook to extend other modules in the included module to remove the need to explicitly extend them _(the other modules)_ at the top of the class definition
