### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by andela-sdamian** [andela-anwocha/checkpoint-one-music-lib#4]
Take advantage of folders to structure your code. At this point, it may seem trivial but it's very important as a developer. In your lib folder, leaving code laying on different aspect without grouping them is really not a good approach. So go create `models folder`,  and `controllers folder` move all your `models` to the model folder and your `music_library_controller.rb` file to your controller folder. This gives your code a good folder structure. Ensure you change the path to `require` in your `music_library_controller.rb` file to make it work.

**Comment by andela-anwocha** [comment]
Sounds good, will effect changes. Thanks
